#!/bin/sh

DAEMON=/usr/bin/content_shell.sh
PIDFILE=/var/run/content_shell.pid
DESC="content_shell"

set -e

do_start() {
	$DAEMON
}

do_stop() {
	start-stop-daemon --stop --name content_shell --quiet
}

case "$1" in
  start)
	echo "Starting $DESC"
	do_start
	;;
  stop)
	echo "Stopping $DESC"
	do_stop
	;;
  restart|force-reload)
	echo "Restarting $DESC"
	do_stop
	sleep 1
	do_start
	;;
  *)
	echo "Usage: $0 {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
